// ------------------------------------------------------------------
// Logic for fixture.html — a single round's detail page. Anyone can
// see who's playing and the groupings once posted; only a signed-in,
// approved member can register their own attendance.
// ------------------------------------------------------------------

const eventId = new URLSearchParams(window.location.search).get("id");
let client;
let currentUser = null;
let isApprovedMember = false;

document.addEventListener("DOMContentLoaded", async () => {
  client = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

    if (!eventId) {
        document.getElementById("fixture-header").innerHTML =
              `<div class="empty-state">No fixture specified. <a href="fixtures.html">Back to fixtures</a>.</div>`;
                  return;
                    }

                      const { data: { session } } = await client.auth.getSession();
                        if (session) {
                            currentUser = session.user;
                                const { data: membership } = await client
                                      .from("memberships")
                                            .select("status")
                                                  .eq("profile_id", currentUser.id)
                                                        .single();
                                                            isApprovedMember = membership?.status === "approved";
                                                              }

                                                                await loadFixtureHeader();
                                                                  await loadAttendance();
                                                                    await loadGroupings();
                                                                    });

                                                                    async function loadFixtureHeader() {
                                                                      const { data: event, error } = await client.from("events").select("*").eq("id", eventId).single();
                                                                        const headerEl = document.getElementById("fixture-header");

                                                                          if (error || !event) {
                                                                              headerEl.innerHTML = `<div class="empty-state">Couldn't find that fixture.</div>`;
                                                                                  return;
                                                                                    }

                                                                                      headerEl.innerHTML = `
                                                                                          <span class="eyebrow">${formatDate(event.event_date)}</span>
                                                                                              <h1>${escapeHtml(event.name)}</h1>
                                                                                                  <p class="small">${escapeHtml(event.venue || "Venue TBC")}${event.address ? " — " + escapeHtml(event.address) : ""}</p>
                                                                                                      ${event.format ? `<p class="small">Format: ${escapeHtml(event.format)}</p>` : ""}
                                                                                                          ${event.notes ? `<p class="small">${escapeHtml(event.notes)}</p>` : ""}
                                                                                                            `;
                                                                                                            }
                                                                                                            
                                                                                                            async function loadAttendance() {
                                                                                                              const actionEl = document.getElementById("attendance-action");
                                                                                                              
                                                                                                                if (!currentUser) {
                                                                                                                    actionEl.innerHTML = `<p class="small"><a href="member.html">Sign in via My Account</a> to register your attendance for this round.</p>`;
                                                                                                                      } else if (!isApprovedMember) {
                                                                                                                          actionEl.innerHTML = `<p class="small">Your member account is still pending approval — once a committee member approves it, you'll be able to register here.</p>`;
                                                                                                                            } else {
                                                                                                                                const { data: myRow } = await client
                                                                                                                                      .from("attendance")
                                                                                                                                            .select("id")
                                                                                                                                                  .eq("event_id", eventId)
                                                                                                                                                        .eq("profile_id", currentUser.id)
                                                                                                                                                              .maybeSingle();
                                                                                                                                                              
                                                                                                                                                                  renderAttendanceButton(!!myRow);
                                                                                                                                                                    }
                                                                                                                                                                    
                                                                                                                                                                      await refreshAttendeeList();
                                                                                                                                                                      }
                                                                                                                                                                      
                                                                                                                                                                      function renderAttendanceButton(isRegistered) {
                                                                                                                                                                        const actionEl = document.getElementById("attendance-action");
                                                                                                                                                                          actionEl.innerHTML = isRegistered
                                                                                                                                                                              ? `<button class="btn btn-outline" id="attendance-btn">Can't make it after all</button>`
                                                                                                                                                                                  : `<button class="btn btn-brass" id="attendance-btn">I'm playing</button>`;
                                                                                                                                                                                  
                                                                                                                                                                                    document.getElementById("attendance-btn").addEventListener("click", async () => {
                                                                                                                                                                                        if (isRegistered) {
                                                                                                                                                                                              await client.from("attendance").delete().eq("event_id", eventId).eq("profile_id", currentUser.id);
                                                                                                                                                                                                  } else {
                                                                                                                                                                                                        await client.from("attendance").insert({ event_id: eventId, profile_id: currentUser.id });
                                                                                                                                                                                                            }
                                                                                                                                                                                                                await loadAttendance();
                                                                                                                                                                                                                  });
                                                                                                                                                                                                                  }
                                                                                                                                                                                                                  
                                                                                                                                                                                                                  async function refreshAttendeeList() {
                                                                                                                                                                                                                    const listEl = document.getElementById("attendee-list");
                                                                                                                                                                                                                      const { data: rows, error } = await client
                                                                                                                                                                                                                          .from("attendance")
                                                                                                                                                                                                                              .select("profiles(display_name)")
                                                                                                                                                                                                                                  .eq("event_id", eventId)
                                                                                                                                                                                                                                      .order("created_at", { ascending: true });
                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                        if (error) {
                                                                                                                                                                                                                                            listEl.innerHTML = `<p class="small">Couldn't load who's playing yet.</p>`;
                                                                                                                                                                                                                                                return;
                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                    if (!rows.length) {
                                                                                                                                                                                                                                                        listEl.innerHTML = `<p class="small">Nobody's registered yet — be the first!</p>`;
                                                                                                                                                                                                                                                            return;
                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                listEl.innerHTML = `<div class="attendee-list">${rows
                                                                                                                                                                                                                                                                    .map(r => `<span class="attendee-chip">${escapeHtml(r.profiles?.display_name || "Member")}</span>`)
                                                                                                                                                                                                                                                                        .join("")}</div>`;
                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                        async function loadGroupings() {
                                                                                                                                                                                                                                                                          const el = document.getElementById("groupings-display");
                                                                                                                                                                                                                                                                            const { data: rows, error } = await client
                                                                                                                                                                                                                                                                                .from("groupings")
                                                                                                                                                                                                                                                                                    .select("group_number, position, profiles(display_name)")
                                                                                                                                                                                                                                                                                        .eq("event_id", eventId)
                                                                                                                                                                                                                                                                                            .order("group_number", { ascending: true })
                                                                                                                                                                                                                                                                                                .order("position", { ascending: true });
                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                  if (error || !rows.length) {
                                                                                                                                                                                                                                                                                                      el.innerHTML = `<p class="small">Groupings will be posted the night before the round.</p>`;
                                                                                                                                                                                                                                                                                                          return;
                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                              const byGroup = new Map();
                                                                                                                                                                                                                                                                                                                for (const r of rows) {
                                                                                                                                                                                                                                                                                                                    if (!byGroup.has(r.group_number)) byGroup.set(r.group_number, []);
                                                                                                                                                                                                                                                                                                                        byGroup.get(r.group_number).push(r.profiles?.display_name || "Member");
                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                            el.innerHTML = Array.from(byGroup.entries())
                                                                                                                                                                                                                                                                                                                                .sort((a, b) => a[0] - b[0])
                                                                                                                                                                                                                                                                                                                                    .map(([num, names]) => `
                                                                                                                                                                                                                                                                                                                                          <div style="margin-bottom:14px;">
                                                                                                                                                                                                                                                                                                                                                  <strong>Group ${num}</strong>
                                                                                                                                                                                                                                                                                                                                                          <div class="attendee-list" style="margin-top:6px;">
                                                                                                                                                                                                                                                                                                                                                                    ${names.map(n => `<span class="attendee-chip">${escapeHtml(n)}</span>`).join("")}
                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                      `).join("");
                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                      function escapeHtml(str) {
                                                                                                                                                                                                                                                                                                                                                                                        if (str == null) return "";
                                                                                                                                                                                                                                                                                                                                                                                          return String(str)
                                                                                                                                                                                                                                                                                                                                                                                              .replaceAll("&", "&amp;")
                                                                                                                                                                                                                                                                                                                                                                                                  .replaceAll("<", "&lt;")
                                                                                                                                                                                                                                                                                                                                                                                                      .replaceAll(">", "&gt;")
                                                                                                                                                                                                                                                                                                                                                                                                          .replaceAll('"', "&quot;");
                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                          
