/* Pairs draw for the admin page. The society runs a pairs competition
   alongside the individual round, and the two draws are independent: a
      player can be in tee group 1 and paired with someone from group 4.
         Pairs live in the same groupings table but tagged group_type =
            "pairs"; the tee draw only reads, writes and clears rows tagged
               "fours". Same shape as the tee draw on purpose - a number against
                  each name - because that is what the committee already knows. */

                  (function () {
                    "use strict";

                      var TYPE = "pairs";
                        var client = null;

                          function escapeHtml(s) {
                              if (s == null) return "";
                                  return String(s).replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
                                    }

                                      function setStatus(msg, isError) {
                                          var el = document.getElementById("pair-status");
                                              if (!el) return;
                                                  el.textContent = msg || "";
                                                      el.className = isError ? "status-msg err" : "small";
                                                        }

                                                          function rowKey(r) { return r.player_id ? "p:" + r.player_id : "m:" + r.profile_id; }

                                                            function summarise() {
                                                                var inputs = Array.prototype.slice.call(document.querySelectorAll("#pair-list .pair-input"));
                                                                    var counts = {};
                                                                        inputs.forEach(function (i) { var v = i.value.trim(); if (v) counts[v] = (counts[v] || 0) + 1; });
                                                                            var numbers = Object.keys(counts);
                                                                                var complete = numbers.filter(function (n) { return counts[n] === 2; }).length;
                                                                                    var singles = numbers.filter(function (n) { return counts[n] === 1; });
                                                                                        var crowded = numbers.filter(function (n) { return counts[n] > 2; });
                                                                                            var waiting = inputs.filter(function (i) { return !i.value.trim(); }).length;
                                                                                                var msg = complete + (complete === 1 ? " pair" : " pairs") + " set";
                                                                                                    if (waiting) msg += " - " + waiting + " not yet paired";
                                                                                                        if (singles.length) msg += " - pair " + singles.join(", ") + " has only one player";
                                                                                                            if (crowded.length) msg += " - pair " + crowded.join(", ") + " has more than two";
                                                                                                                setStatus(msg, singles.length > 0 || crowded.length > 0);
                                                                                                                  }
                                                                                                                  
                                                                                                                    async function refreshPairList(eventId) {
                                                                                                                        var el = document.getElementById("pair-list");
                                                                                                                            if (!el || !eventId) return;
                                                                                                                                var attRes = await client.from("attendance").select("profile_id, player_id").eq("event_id", eventId).order("created_at", { ascending: true });
                                                                                                                                    if (attRes.error) { el.innerHTML = '<p class="status-msg err">Could not load the round.</p>'; return; }
                                                                                                                                        var attendance = attRes.data || [];
                                                                                                                                            if (!attendance.length) { el.innerHTML = '<p class="small">Nobody is on this round yet, so there are no pairs to draw.</p>'; setStatus(""); return; }
                                                                                                                                                var pairRes = await client.from("groupings").select("profile_id, player_id, group_number").eq("event_id", eventId).eq("group_type", TYPE);
                                                                                                                                                    var existing = {};
                                                                                                                                                        (pairRes.data || []).forEach(function (g) { existing[rowKey(g)] = g.group_number; });
                                                                                                                                                            var profileIds = attendance.map(function (a) { return a.profile_id; }).filter(Boolean);
                                                                                                                                                                var profById = {};
                                                                                                                                                                    if (profileIds.length) { var pRes = await client.from("profiles").select("id, display_name").in("id", profileIds); (pRes.data || []).forEach(function (p) { profById[p.id] = p.display_name; }); }
                                                                                                                                                                        var playerIds = attendance.map(function (a) { return a.player_id; }).filter(Boolean);
                                                                                                                                                                            var playerById = {};
                                                                                                                                                                                if (playerIds.length) { var plRes = await client.from("players").select("id, name").in("id", playerIds); (plRes.data || []).forEach(function (p) { playerById[p.id] = p.name; }); }
                                                                                                                                                                                    el.innerHTML = attendance.map(function (a) {
                                                                                                                                                                                          var name = a.player_id ? (playerById[a.player_id] || "Player") : (profById[a.profile_id] || "Member");
                                                                                                                                                                                                var value = existing[rowKey(a)] != null ? existing[rowKey(a)] : "";
                                                                                                                                                                                                      return '<div style="display:flex; align-items:center; justify-content:space-between; gap:12px; padding:8px 0; border-bottom:1px solid var(--line);"><span>' + escapeHtml(name) + '</span><input type="number" min="1" max="30" step="1" class="pair-input" placeholder="Pair" style="width:88px;" data-profile-id="' + (a.profile_id || "") + '" data-player-id="' + (a.player_id || "") + '" value="' + value + '"></div>';
                                                                                                                                                                                                          }).join("");
                                                                                                                                                                                                              summarise();
                                                                                                                                                                                                                }
                                                                                                                                                                                                                
                                                                                                                                                                                                                  function autofillPairs() {
                                                                                                                                                                                                                      Array.prototype.slice.call(document.querySelectorAll("#pair-list .pair-input")).forEach(function (input, i) { input.value = Math.floor(i / 2) + 1; });
                                                                                                                                                                                                                          summarise();
                                                                                                                                                                                                                            }
                                                                                                                                                                                                                            
                                                                                                                                                                                                                              function clearPairs() {
                                                                                                                                                                                                                                  Array.prototype.slice.call(document.querySelectorAll("#pair-list .pair-input")).forEach(function (i) { i.value = ""; });
                                                                                                                                                                                                                                      summarise();
                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                          async function savePairs() {
                                                                                                                                                                                                                                              var select = document.getElementById("pair-event-select");
                                                                                                                                                                                                                                                  var eventId = select ? select.value : null;
                                                                                                                                                                                                                                                      if (!eventId) return;
                                                                                                                                                                                                                                                          var rows = Array.prototype.slice.call(document.querySelectorAll("#pair-list .pair-input")).filter(function (input) { return input.value !== ""; }).map(function (input, i) {
                                                                                                                                                                                                                                                                return { event_id: eventId, profile_id: input.dataset.profileId || null, player_id: input.dataset.playerId || null, group_number: Number(input.value), group_type: TYPE, position: i };
                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                        setStatus("Saving...");
                                                                                                                                                                                                                                                                            var clear = await client.from("groupings").delete().eq("event_id", eventId).eq("group_type", TYPE);
                                                                                                                                                                                                                                                                                if (clear.error) { setStatus(clear.error.message, true); return; }
                                                                                                                                                                                                                                                                                    if (rows.length) { var ins = await client.from("groupings").insert(rows); if (ins.error) { setStatus(ins.error.message, true); return; } }
                                                                                                                                                                                                                                                                                        setStatus("Pairs saved.");
                                                                                                                                                                                                                                                                                            summarise();
                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                async function start() {
                                                                                                                                                                                                                                                                                                    var host = document.getElementById("pair-list");
                                                                                                                                                                                                                                                                                                        if (!host || !window.supabase || typeof SUPABASE_URL === "undefined") return;
                                                                                                                                                                                                                                                                                                            client = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
                                                                                                                                                                                                                                                                                                                var sess = await client.auth.getSession();
                                                                                                                                                                                                                                                                                                                    if (!sess || !sess.data || !sess.data.session) return;
                                                                                                                                                                                                                                                                                                                        var evRes = await client.from("events").select("id, name, event_date").order("event_date", { ascending: false });
                                                                                                                                                                                                                                                                                                                            var events = evRes.data || [];
                                                                                                                                                                                                                                                                                                                                var select = document.getElementById("pair-event-select");
                                                                                                                                                                                                                                                                                                                                    if (select) {
                                                                                                                                                                                                                                                                                                                                          select.innerHTML = events.map(function (e) { return '<option value="' + e.id + '">' + escapeHtml(e.name) + " - " + e.event_date + "</option>"; }).join("");
                                                                                                                                                                                                                                                                                                                                                select.onchange = function () { refreshPairList(select.value); };
                                                                                                                                                                                                                                                                                                                                                      if (events.length) await refreshPairList(select.value);
                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                              var auto = document.getElementById("autofill-pairs-btn");
                                                                                                                                                                                                                                                                                                                                                                  if (auto) auto.addEventListener("click", autofillPairs);
                                                                                                                                                                                                                                                                                                                                                                      var clearBtn = document.getElementById("clear-pairs-btn");
                                                                                                                                                                                                                                                                                                                                                                          if (clearBtn) clearBtn.addEventListener("click", clearPairs);
                                                                                                                                                                                                                                                                                                                                                                              var save = document.getElementById("save-pairs-btn");
                                                                                                                                                                                                                                                                                                                                                                                  if (save) save.addEventListener("click", savePairs);
                                                                                                                                                                                                                                                                                                                                                                                      host.addEventListener("input", function (e) { if (e.target && e.target.classList && e.target.classList.contains("pair-input")) summarise(); });
                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                          if (document.readyState === "loading") { document.addEventListener("DOMContentLoaded", start); } else { start(); }
                                                                                                                                                                                                                                                                                                                                                                                          })();
                                                                                                                                                                                                                                                                                                                                                                                          
